### ISSUE TITLE
Add oneliner command to README.md which would just-work without deeply looking

### ISSUE THREAD

**Issue by vini-nu** [Kakoen/valheim-save-tools#29]
Add oneliner command example to README.md which would just-work without deeply looking into details. It is too much text to read to just parse a database for simple look.

**Comment by Vinigas** [comment]
`java -jar valheim-save-tools.jar mysave.db mysave.json` decode from savefile to json
`java -jar valheim-save-tools.jar mysave.json mysave.db` encode from json to savefile

**Comment by Kakoen** [comment]
Added!
