### ISSUE TITLE
How do compass directions relate to x/y/z coordinates?

### ISSUE THREAD

**Issue by JoshuaWise** [Kakoen/valheim-save-tools#7]
I wrote a script that searches the JSON for the string `"Vendor_BlackForest"` which is apparently the name of Haldor. I found some coordinates associated with it, which I'm assuming is where he's located (for me, he's very far in the negative Z direction, and slightly less far in the positive X direction... The Y direction seems to measure altitude). Do you know, or is there a way to know how X and Z relate to North/South/East/West in game?

**Comment by Kakoen** [comment]
The X coordinate measures West / East. A higher X means more east.
The Z coordinate measures South / North. A higher Z means more north.
Y is indeed altitude.
Coordinates can be roughly measured in meters.

**Comment by JoshuaWise** [comment]
Thank you! 👍 Sorry for not closing this issue myself, I was out of town.
